import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Timeline from '@/components/Timeline'
import CardGrid from '@/components/CardGrid'
import Sponsor from '@/components/Sponsors'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar />
      <Hero />
      <CardGrid />
      <Timeline />
      <Sponsor />
      <Footer />
    </html>
  )
}
